# Generated by Django 5.2.6 on 2025-09-10 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('preferred_language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English')], default='hi', max_length=5)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('village', models.CharField(blank=True, max_length=128)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Farm', max_length=80)),
                ('area_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('area_unit', models.CharField(choices=[('acre', 'Acre'), ('hectare', 'Hectare')], default='acre', max_length=10)),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy'), ('clay', 'Clayey'), ('sandy', 'Sandy'), ('alluvial', 'Alluvial')], default='loamy', max_length=20)),
                ('irrigation', models.CharField(blank=True, default='', max_length=40)),
                ('crop_current', models.CharField(blank=True, max_length=40)),
                ('sow_date', models.DateField(blank=True, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('village', models.CharField(blank=True, max_length=128)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='main.farmerprofile')),
            ],
        ),
    ]
