# Generated by Django 5.2.6 on 2025-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='irrigation_source',
            field=models.CharField(blank=True, choices=[('tube_well', 'Tube Well'), ('canal', 'Canal'), ('rainfed', 'Rainfed'), ('drip', 'Drip Irrigation'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='nearby_mandi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='prefers_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='selling_channel',
            field=models.CharField(blank=True, choices=[('mandi', 'Local Mandi'), ('direct', 'Direct Buyers'), ('fpo', 'FPO / Cooperative'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='used_fertilizers',
            field=models.CharField(blank=True, help_text='Comma-separated list of fertilizers', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='used_pesticides',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='water_availability',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('sufficient', 'Sufficient')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('alluvial', 'Alluvial'), ('loamy', 'Loamy'), ('clayey', 'Clayey'), ('sandy', 'Sandy'), ('laterite', 'Laterite'), ('black', 'Black'), ('red', 'Red')], max_length=50, null=True),
        ),
    ]
