# Generated by Django 5.2.6 on 2025-09-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_farm_irrigation_source_farm_nearby_mandi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='irrigation',
            new_name='last_irrigation',
        ),
        migrations.AlterField(
            model_name='farm',
            name='irrigation_source',
            field=models.CharField(blank=True, choices=[('tube_well', 'Tube Well'), ('canal', 'Canal'), ('rainfed', 'Rainfed'), ('drip', 'Drip Irrigation'), ('other', 'Other')], default='tube_well', max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='nearby_mandi',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='selling_channel',
            field=models.CharField(blank=True, choices=[('mandi', 'Local Mandi'), ('direct', 'Direct Buyers'), ('fpo', 'FPO / Cooperative'), ('other', 'Other')], default='mandi', max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(choices=[('alluvial', 'Alluvial'), ('loamy', 'Loamy'), ('clayey', 'Clayey'), ('sandy', 'Sandy'), ('laterite', 'Laterite'), ('black', 'Black'), ('red', 'Red')], default='loamy', max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='used_fertilizers',
            field=models.CharField(blank=True, default='no', help_text='Comma-separated list of fertilizers', max_length=200),
        ),
        migrations.AlterField(
            model_name='farm',
            name='water_availability',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('sufficient', 'Sufficient')], default='low', max_length=20),
        ),
    ]
