# Generated by Django 5.2.6 on 2025-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_irrigation_farm_last_irrigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='nitrogen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='phosphorus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='potassium',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
    ]
